// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB2aCsGeYKJBiDyV19BKa6blXRhu7x1qGg',
    appId: '1:18696343719:web:e8b6f9fa33dc817d848b82',
    messagingSenderId: '18696343719',
    projectId: 'meblog-76831',
    authDomain: 'meblog-76831.firebaseapp.com',
    storageBucket: 'meblog-76831.firebasestorage.app',
    measurementId: 'G-TWLV6MHY12',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCNWChmc4ZVMQHyOfz-4ttGUHc9LL0V-bk',
    appId: '1:18696343719:android:cd37269acacbe23b848b82',
    messagingSenderId: '18696343719',
    projectId: 'meblog-76831',
    storageBucket: 'meblog-76831.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAol7lNQDfKeINFgCEA9Xpa7Ct0wnoPUuY',
    appId: '1:18696343719:ios:a3dde77a10967ee2848b82',
    messagingSenderId: '18696343719',
    projectId: 'meblog-76831',
    storageBucket: 'meblog-76831.firebasestorage.app',
    iosBundleId: 'com.example.meblogs',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAol7lNQDfKeINFgCEA9Xpa7Ct0wnoPUuY',
    appId: '1:18696343719:ios:a3dde77a10967ee2848b82',
    messagingSenderId: '18696343719',
    projectId: 'meblog-76831',
    storageBucket: 'meblog-76831.firebasestorage.app',
    iosBundleId: 'com.example.meblogs',
  );

}